# Generated by Django 6.0 on 2026-02-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('shoot_type', models.CharField(choices=[('wedding', 'Wedding'), ('lifestyle', 'Lifestyle'), ('other', 'Other Shoot')], max_length=20)),
            ],
        ),
    ]
